### ISSUE TITLE
License

### ISSUE THREAD

**Issue by llogiq** [Geal/mutant#3]
@Geal we should choose a license. I'm OK with most OSI-approved ones, but would favor one of two options:
- MIT + Apache seems to be the mostly used in other Rust projects (and would be my prime choice for libraries)
- MPL is used by clippy, and if I understand correctly, using it would allow us to exchange code with it

So what do you think? Let's choose one and add it to `README.md` and `Cargo.toml`

Btw. I have the beginnings of a lint plugin that will find valid mutations for us.

**Comment by Geal** [comment]
I just added a MIT license, how do I specify MIT+Apache?

**Comment by llogiq** [comment]
`license="MIT+Apache2"`

**Comment by Geal** [comment]
ok, that was easy :)

**Comment by llogiq** [comment]
Thank you! :+1:
